# SPDX-FileCopyrightText: 2026 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: skills

"""Shared generic vocabulary for W&B run-table helper heuristics.

These lists intentionally describe broad ML conventions rather than individual
projects, eval rows, or answer keys.
"""

MINIMIZE_METRIC_TOKENS = [
    "loss",
    "error",
    "err",
    "nll",
    "cross_entropy",
    "ce",
    "bpb",
    "bits_per_byte",
    "perplex",
    "ppl",
    "wer",
    "cer",
    "mae",
    "mse",
    "rmse",
    "latency",
    "runtime",
    "duration",
    "time",
    "cost",
    "fid",
    "frechet",
    "fréchet",
    "distance",
]

METRIC_HINT_ALIASES = {
    "accuracy": ["accuracy", "acc", "top1", "top_1", "top5", "top_5"],
    "acc": ["accuracy", "acc", "top1", "top_1", "top5", "top_5"],
    "auc": ["auc", "auroc", "roc_auc"],
    "auroc": ["auroc", "auc", "roc_auc"],
    "bleu": ["bleu", "sacrebleu"],
    "cer": ["cer", "char_error_rate"],
    "em": ["exact_match", "em"],
    "error": ["error", "err", "failure"],
    "f1": ["f1", "f1_score"],
    "fid": ["fid", "frechet", "fréchet"],
    "loss": ["loss", "nll", "cross_entropy", "ce_loss"],
    "val_loss": ["best_val_loss", "val_loss", "validation_loss", "validation/best_loss", "eval/loss"],
    "validation loss": ["best_val_loss", "val_loss", "validation_loss", "validation/best_loss", "eval/loss"],
    "best validation loss": ["best_val_loss", "val_loss", "validation_loss", "validation/best_loss"],
    "map": ["map", "mean_average_precision", "average_precision", "ap"],
    "mAP": ["map", "mean_average_precision", "average_precision", "ap"],
    "perplexity": ["perplexity", "ppl"],
    "ppl": ["perplexity", "ppl"],
    "precision": ["precision", "ppv"],
    "recall": ["recall", "sensitivity", "tpr"],
    "reward": ["reward", "return", "score", "win_rate"],
    "rouge": ["rouge", "rouge1", "rouge2", "rougel"],
    "wer": ["wer", "word_error_rate"],
}

COMPREHENSIVE_METRIC_TOKENS = [
    "overall",
    "mean",
    "avg",
    "average",
    "macro",
    "micro",
    "weighted",
    "balanced",
    "final",
    "best",
    "eval",
    "validation",
    "valid",
    "val",
    "test",
    "heldout",
    "dev",
    "primary",
    "aggregate",
    "combined",
]

COMPREHENSIVE_METRIC_PATTERNS = [
    r"\d+(?:\.\d+)?\s*[:_-]\s*\d+(?:\.\d+)?",
    r"(?:macro|micro|weighted|mean|avg|overall)[/_-]",
    r"[/_-](?:macro|micro|weighted|mean|avg|overall)",
]

PERFORMANCE_METRIC_TOKENS = [
    "accuracy",
    "acc",
    "auc",
    "auroc",
    "ap",
    "map",
    "average_precision",
    "bleu",
    "rouge",
    "f1",
    "precision",
    "recall",
    "specificity",
    "sensitivity",
    "mcc",
    "exact_match",
    "em",
    "win_rate",
    "reward",
    "return",
    "score",
    "success",
    "pass_rate",
    "solve_rate",
    "fid",
    "frechet",
    "fréchet",
    "distance",
    "loss",
    "error",
    "perplexity",
    "ppl",
    "wer",
    "cer",
    "mae",
    "mse",
    "rmse",
    "latency",
    "throughput",
    "tokens_per_second",
    "samples_per_second",
]

HPARAM_PRIORITY_KEYS = [
    "learning_rate",
    "lr",
    "max_lr",
    "min_lr",
    "init_lr",
    "init_lr_frac",
    "warmup_steps",
    "warmup_ratio",
    "batch_size",
    "bs",
    "per_device_train_batch_size",
    "per_device_eval_batch_size",
    "train_batch_size",
    "eval_batch_size",
    "micro_batch_size",
    "mini_batch_size",
    "gradient_accumulation_steps",
    "accumulate_grad_batches",
    "weight_decay",
    "wd",
    "adam_beta1",
    "adam_beta2",
    "adam_epsilon",
    "epsilon",
    "eps",
    "max_grad_norm",
    "grad_clip",
    "cliprange",
    "cliprange_value",
    "optimizer",
    "optim",
    "scheduler",
    "lr_scheduler_type",
    "lr_scheduler_kwargs",
    "dropout",
    "attention_dropout",
    "label_smoothing_factor",
    "bf16",
    "fp16",
    "tf32",
    "gradient_checkpointing",
    "deepspeed",
    "fsdp",
    "num_train_epochs",
    "epochs",
    "epoch",
    "ep",
    "max_steps",
    "steps",
    "logging_steps",
    "eval_steps",
    "save_steps",
    "seed",
    "data_seed",
    "model",
    "model_name",
    "model_name_or_path",
    "pretrained_model_name_or_path",
    "weights",
    "model_class",
    "model_family",
    "family",
    "architecture",
    "arch",
    "hidden_dim",
    "hidden_size",
    "width",
    "depth",
    "num_layers",
    "n_layers",
    "num_hidden_layers",
    "num_attention_heads",
    "heads",
    "parameter_count",
    "checkpoint",
    "dataset",
    "dataset_name",
    "data",
    "flow_type",
    "objective",
    "loss_type",
    "materialization",
    "aug_channels",
    "augmentation",
    "in_channels",
    "input_channels",
    "total_input_channels",
    "max_seq_length",
    "seq_length",
    "block_size",
    "packing",
    "nfe",
    "num_inference_steps",
    "inference_steps",
    "num_ppo_epochs",
    "ppo_epochs",
    "kl_coef",
    "init_kl_coef",
    "target_kl",
    "kl_penalty",
    "beta",
    "gamma",
    "lam",
    "vf_coef",
    "temperature",
    "top_p",
    "top_k",
    "num_beams",
    "num_sample_generations",
    "response_length",
    "max_new_tokens",
    "reward_model",
    "reward_model_path",
    "sft_model_path",
    "image_size",
    "input_size",
    "resolution",
]

HPARAM_KEY_TOKENS = [
    "lr",
    "learning",
    "warmup",
    "batch",
    "dropout",
    "decay",
    "optim",
    "sched",
    "epsilon",
    "grad",
    "clip",
    "weight",
    "image",
    "resolution",
    "input",
    "data",
    "dataset",
    "model",
    "arch",
    "hidden",
    "width",
    "depth",
    "layer",
    "head",
    "parameter",
    "flow",
    "objective",
    "materialization",
    "aug",
    "augmentation",
    "channel",
    "nfe",
    "inference",
    "checkpoint",
    "epoch",
    "step",
    "seed",
    "precision",
    "fp16",
    "bf16",
    "tf32",
    "deepspeed",
    "fsdp",
    "sequence",
    "seq",
    "block_size",
    "packing",
    "kl",
    "beta",
    "gamma",
    "lambda",
    "lam",
    "reward",
    "temperature",
    "top_p",
    "top_k",
    "beam",
    "tokens",
    "generate",
]

CONFIG_AXIS_TOKENS = sorted(set(HPARAM_KEY_TOKENS) | {
    "optimizer",
    "size",
})

CONFIG_OVERVIEW_TOKENS = sorted(set(HPARAM_KEY_TOKENS) | {
    "framework",
    "job",
    "loss",
    "method",
    "mode",
    "optimizer",
    "output",
    "path",
    "size",
    "task",
    "trainer",
})

LAYER_METRIC_TOKENS = [
    "layer",
    "block",
]

LAYER_STAT_TOKENS = [
    "weight",
    "norm",
    "grad",
    "activation",
    "variance",
    "mean",
    "std",
]

GPU_TRAINING_EXCLUDE_TERMS = [
    "eval",
    "toy",
    "smoke",
    "test",
    "data",
    "publish",
    "create",
    "generation",
    "inference",
    "predict",
]

STABILITY_PRIMARY_LOSS_TOKENS = [
    "loss_fm",
    "loss_ce",
    "loss_mlm",
    "loss_lm",
    "objective_loss",
    "policy_loss",
    "value_loss",
    "actor_loss",
    "critic_loss",
]

STABILITY_REGULARIZER_LOSS_TOKENS = [
    "loss_kl",
    "kl_loss",
    "kl_div",
    "kl",
    "regularizer",
    "penalty",
]

STABILITY_GRADIENT_TOKENS = [
    "grad_norm",
    "gradient_norm",
    "global_grad_norm",
    "grad/global_norm",
    "gradients/norm",
]
